### ISSUE TITLE
Sample code calls begin function where prototype and implementation does not exist

### ISSUE THREAD

**Issue by apateluk** [adafruit/Adafruit_MCP3008#3]
Looking at the sample, it calls adc.begin() however both begin prototypes take parameters. What function does this call ?

**Comment by caternuson** [comment]
Defaults are provided in the header:
https://github.com/adafruit/Adafruit_MCP3008/blob/master/Adafruit_MCP3008.h#L37
So this:
```
adc.begin();
```
is equivalent to this:
```
adc.being(SS, &SPI);
```
