### ISSUE TITLE
missing file ?

### ISSUE THREAD

**Issue by simontpellier** [adafruit/Adafruit_MCP3008#8]
Hi !

I get a fatal error with this comment :

"...libraries\Adafruit_MCP3008-master/Adafruit_MCP3008.h:22:32: fatal error: Adafruit_SPIDevice.h: No such file or directory"

?? 
thanks in advance

**Comment by caternuson** [comment]
You need to install the BusIO library:
https://github.com/adafruit/Adafruit_BusIO

**Comment by simontpellier** [comment]
> 
> 
> You need to install the BusIO library:
> https://github.com/adafruit/Adafruit_BusIO

many thanks !!
